<?php
/**
 * Created by PhpStorm.
 * User: Jackson
 * Date: 05/01/2016
 * Time: 01:15
 */

namespace OpenChurch\Models;


class Membro extends Model
{
    protected $table = 'membros';

    public function findWithRelated(array $identifier)
    {
        $m = parent::find($identifier); // TODO: Change the autogenerated stub
        if (!$m) return null;
        $pessoa_manager = new Pessoa($this->db);
        if (isset($m->pessoa_id)) {
            $m->pessoa = $pessoa_manager->find(['id' => $m->pessoa_id]);
        }
        return $m;
    }

}